COPY INTO RAW.AIR_POLLUTION.RAW_AIR_POLLUTION (RAW_PAYLOAD, _SOURCE_FILE)
FROM (
    SELECT 
        $1,
        METADATA$FILENAME
    FROM @"s3_stage"/bronze/air_pollution/
)
FILE_FORMAT = (TYPE = 'JSON')
ON_ERROR = 'ABORT_STATEMENT';